#!/usr/bin/env python

#Written By: Grace Lainez
#Project 3 for ECE 2524
#this script will create a one player game of hangman to be executed
#on the terminal. The words for the games will be pre-set within the code
#The user will have 10 tries before they lose 
#(10 tries for head, body, 2 legs, 2 arms, 2 hands, and 2 feet)
#There are 21 words in the word bank

import random
words = ['rain', 'sun', 'happy', 'sad', 'enlightened', 'motivated', 'coffee', 'starbucks', 'work', 'engineering', 'computers', 'McPherson', 'study', 'finals', 'beautiful', 'winter', 'umbrella', 'cake', 'motivated', 'blacksburg', 'hunger']
print "Welcome to Python hangman!"
indice = random.randrange(0,20)
print "Your word is:",
print words[indice]
